### ISSUE TITLE
Désinscription

### ISSUE THREAD

**Issue by juliensarton** [ajoron/fitfactory-events#48]
Changer la phrase "Souhaitez vous réellement vous désinscrire du prochain événément
Garmin Team Running" par "Vous souhaitez vous désinscrire de la prochaine session du
Garmin Team Running ?"

+ rien ne se passe quand je clic sur "confirmer" : la petite roue bleu tourne durant 2 sec et plus rien (Chrome)

**Comment by juliensarton** [comment]
eh ben en fait j'ai bien recu les emails de confirmation de ma désinscription (autant de fois que j'ai cliqué sur le bouton d'ailleurs), mais il n'y a pas eu de message sur la plateforme me confirmant que je m'étais bien désinscris

**Comment by ajoron** [comment]
Corrigé
