### ISSUE TITLE
Bouton suite à inscription liste principale et liste d'attente

### ISSUE THREAD

**Issue by ajoron** [ajoron/fitfactory-events#67]
Revoir les messages 

Bouton Rejoignez nous sur facebook
Bouton voir les produits Garmin

**Comment by juliensarton** [comment]
Message après la confirmation de l'inscription : 

Bienvenue dans le Team ! (laisser plus d'espace au dessus, pour ne pas être collé au "3") 

Votre inscription à la session du Garmin Team Running est confirmée. Un email automatique vient de vous être envoyé, vérifiez dans le dossier SPAM de votre messagerie si vous n'avez rien reçu. 

Pour permettre aux cochs de préparer au mieux l'entraînement, n'oubliez pas de compléter votre profil en indiquant votre niveau de running, votre prochain challenge ainsi que la montre avec laquelle vous courez.

Assurez-vous d'avoir lu et compris les conditions générales avant de participer à l’évènement.(mettre lien vers la page des conditions générales)
.
Remplacer le bouton "Voir les participants" par "Voir toutes les montres running" (lien = https://buy.garmin.com/fr-FR/FR/cIntoSports-cRunning-p1.html ) + "Nous suivre sur Facebook" (lien = https://www.facebook.com/GarminFrance?fref=ts) 



>> Agrandir l'interligne d'une manière générale
